// src/routes/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";

    let statusPages = [];

    onMount(async () => {
        try {
            const res = await fetch("/api/status_pages");
            if (!res.ok) {
                throw new Error("Failed to fetch status pages");
            }
            statusPages = await res.json();
        } catch (error) {
            console.error("Error fetching status pages:", error);
        }
    })
</script>

<div class="w-full h-screen flex flex-col">
    <a href="/dashboard" class="absolute right-4 top-2 text-sm text-neutral-300 hover:underline">go to dashboard →</a>

    <div class="m-auto w-full md:w-1/2 flex flex-col">
        {#if statusPages.length > 0}
            <h1 class="text-3xl font-bold text-neutral-300 w-full text-center mb-2">Status Pages</h1>
        
            {#each statusPages as page}
                <div class="flex flex-col flex-1 p-2 border rounded-md m-2">
                    <div class="flex">
                        <h2 class="text-lg font-semibold text-neutral-300">{page.name}</h2>
                        
                        <a href={`/status/${page.slug}`} class="ml-auto my-auto text-sm text-neutral-300 hover:underline">
                            open →
                        </a>
                    </div>

                    <p class="text-sm text-neutral-400">{page.description}</p>

                    <div class="xl:flex text-sm w-full mt-2">
                        <div class="flex mb-1 xl:mb-0 w-full">
                            <p class="text-neutral-300 border px-2 rounded-md w-1/2">up/down: 
                                <span class="text-green-400">{page.monitors_up}</span>
                                /
                                <span class="text-red-400">{page.monitor_count - page.monitors_up}</span>
                            </p>

                            <p class="text-neutral-300 ml-2 border px-2 rounded-md w-1/2">avg. ping: 
                                <span class="text-neutral-300">{page.avg_ping ? page.avg_ping.toString() + "ms" : "N/A"}</span>
                            </p>
                        </div>

                        <div class="flex w-full">
                            <p class="text-neutral-300 xl:ml-2 border px-2 rounded-md w-1/2">avg. uptime: 
                                <span class="text-neutral-300">{page.avg_uptime ? page.avg_uptime.toFixed(2) + "%" : "N/A"}</span>
                            </p>

                            {#if page.status === "up"}
                                <p class="text-green-400 ml-2 border px-2 rounded-md w-1/2">online :D</p>
                            {:else if page.status === "down"}
                                <p class="text-red-400 ml-2 border px-2 rounded-md w-1/2">offline :c</p>
                            {:else if page.status === "degraded"}
                                <p class="text-yellow-400 ml-2 border px-2 rounded-md w-1/2">
                                    degraded :/
                                </p>
                            {:else}
                                <p class="text-neutral-400 ml-2 border px-2 rounded-md w-1/2">status unknown</p>
                            {/if}
                        </div>
                    </div>
                </div>
            {/each}
        {:else}
            <p class="text-neutral-300 mx-auto">no status pages found :(</p>
        {/if}
    </div>
</div>

// src/routes/index.tsx
import { createSignal, onMount, Show, createMemo } from "solid-js";
import { Badge } from "~/components/ui/badge";

import { Alert, AlertDescription, AlertTitle } from "~/components/ui/alert";

export default function Index() {
  const [data, setData] = createSignal({});

  const [visibleHeartbeats, setVisibleHeartbeats] = createSignal(50);
  const [infoLabels, setInfoLabels] = createSignal({});

  onMount(() => {
    const updateScreenSize = () => {
      if (window.innerWidth >= 1400) {
        setVisibleHeartbeats(50);
      } else if (window.innerWidth >= 1200) {
        setVisibleHeartbeats(40);
      } else {
        setVisibleHeartbeats(30);
      }
    };

    window.addEventListener("resize", updateScreenSize);
    updateScreenSize();

    fetch("/api/data")
      .then((res) => res.json())
      .then((data) => setData(data));

    setInterval(() => {
      fetch("/api/data")
        .then((res) => res.json())
        .then((data) => setData(data));
    }, 60000);

    return () => window.removeEventListener("resize", updateScreenSize);
  });

  return (
    <main class="h-screen w-full flex flex-col items-center">
      <div class="mt-10 inline-block">
        <h1
          class="text-7xl font-bold gradient text-center"
          innerHTML={data().title}
        ></h1>
        <p class="text-2xl text-center" innerHTML={data().description}></p>

        <Show when={data().alert?.show}>
          <Alert class="mt-8">
            <AlertTitle class="text-lg font-bold">
              {data().alert?.title}
            </AlertTitle>
            <AlertDescription>{data().alert?.description}</AlertDescription>
          </Alert>
        </Show>
      </div>

      <div class="mt-10 w-[90%] md:w-1/2 ">
        <Show when={data().monitors?.length == 0}>
          <p class="text-center">No monitors found</p>
        </Show>
        <Show when={data().monitors?.length > 0}>
          <div class="flex flex-col w-full h-full">
            <Badge variant="outline" class="ml-auto bg-background">
              <span class="h-3 w-3 rounded-full bg-green-400 mr-1"></span>
              <span class="mt-[3px]">Online</span>
              <span class="h-3 w-3 rounded-full bg-yellow-200 ml-2 mr-1"></span>{" "}
              <span class="mt-[3px]">Degraded</span>
              <span class="h-3 w-3 rounded-full bg-red-400 ml-2 mr-1"></span>{" "}
              <span class="mt-[3px]">Down</span>
              <span class="h-3 w-3 rounded-full bg-gray-400 ml-2 mr-1"></span>{" "}
              <span class="mt-[3px]">Paused</span>
            </Badge>
            <div class="mt-2 border-[1px] border-border rounded-lg bg-background h-full">
              {data().monitors?.map((monitor, index) => (
                <div
                  class={`flex p-5 flex-col lg:flex-row ${
                    index !== data().monitors.length - 1 ? "border-b-[1px]" : ""
                  }`}
                >
                  <div class="flex items-center">
                    <Show when={monitor.heartbeats[0]?.status == "up"}>
                      <span class="bg-green-400 mr-2 rounded-full h-5 w-5"></span>
                    </Show>
                    <Show when={monitor.heartbeats[0]?.status == "paused"}>
                      <span class="bg-gray-400 mr-2 rounded-full h-5 w-5"></span>
                    </Show>
                    <Show when={monitor.heartbeats[0]?.status == "down"}>
                      <span class="bg-red-400 mr-2 rounded-full h-5 w-5"></span>
                    </Show>
                    <Show when={monitor.heartbeats[0]?.status == "degraded"}>
                      <span class="bg-yellow-200 mr-2 rounded-full h-5 w-5"></span>
                    </Show>
                    <h1 class="font-bold text-lg mt-1">{monitor.name}</h1>
                  </div>
                  <div class="ml-auto flex flex-col min-h-4">
                    <div class="self-end">
                      <Show when={monitor.avg_ping}>
                        <Badge class="self-end mr-2 w-fit rounded-xl">
                          Avg: {monitor.avg_ping?.toFixed(0)}ms
                        </Badge>
                      </Show>
                      <Badge class="self-end mr-2 w-fit rounded-xl">
                        {monitor.heartbeats[0]?.ping}ms
                      </Badge>
                      <Badge class="self-end w-fit rounded-xl">
                        {monitor.uptime
                          ? monitor.uptime?.toFixed(1) + "%"
                          : "?"}
                      </Badge>
                    </div>
                    <div class="flex justify-end">
                      {monitor.heartbeats
                        ?.slice(0, visibleHeartbeats())
                        .toReversed()
                        .map((ping) => (
                          <div
                            class="mt-1 min-h-8"
                            onMouseOver={() => {
                              setInfoLabels({
                                [monitor.id.toString()]: ping,
                              });
                            }}
                            onMouseLeave={() => {
                              setInfoLabels({});
                            }}
                          >
                            <Show when={ping.status == "up"}>
                              <div class="w-1 h-full mx-0.5 rounded-full bg-green-400"></div>
                            </Show>
                            <Show when={ping.status == "paused"}>
                              <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-gray-400"></div>
                            </Show>
                            <Show when={ping.status == "degraded"}>
                              <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-yellow-200"></div>
                            </Show>
                            <Show when={ping.status == "down"}>
                              <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-red-400"></div>
                            </Show>
                          </div>
                        ))}
                    </div>
                    <div class="min-h-[25px]">
                      <Show when={infoLabels()[monitor.id.toString()]}>
                        <Show
                          when={
                            infoLabels()[monitor.id.toString()].status == "up"
                          }
                        >
                          <p class="text-sm mt-1 text-green-400">{`${infoLabels()[monitor.id.toString()].time} - ${infoLabels()[monitor.id.toString()].ping}ms`}</p>
                        </Show>
                        <Show
                          when={
                            infoLabels()[monitor.id.toString()].status ==
                            "degraded"
                          }
                        >
                          <p class="text-sm mt-1 text-yellow-200">{`${infoLabels()[monitor.id.toString()].time} - ${infoLabels()[monitor.id.toString()].ping}ms`}</p>
                        </Show>
                        <Show
                          when={
                            infoLabels()[monitor.id.toString()].status == "down"
                          }
                        >
                          <p class="text-sm mt-1 text-red-400">{`${infoLabels()[monitor.id.toString()].time} -
                            ${infoLabels()[monitor.id.toString()].code != 0 ? "Status: " + infoLabels()[monitor.id.toString()].code : "Down"}`}</p>
                        </Show>
                        <Show
                          when={
                            infoLabels()[monitor.id.toString()].status ==
                            "paused"
                          }
                        >
                          <p class="text-sm mt-1 text-gray-400">{`${infoLabels()[monitor.id.toString()].time} - Paused`}</p>
                        </Show>
                      </Show>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </Show>
      </div>
      <div class="mt-auto">
        <footer
          class="mt-6 mb-2 text-center text-muted-foreground"
          innerHTML={data().footer}
        ></footer>
      </div>
    </main>
  );
}
