// src/routes/status/[slug]/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { onMount } from "svelte";

    export let data: { slug: string };

    let statusPage = {
        name: "",
        slug: data.slug,
        description: "",
        monitors: [],
    };

    let isPhone = false;

    onMount(async () => {
        try {
            const res = await fetch(`/api/status_pages/${data.slug}`);

            if (!res.ok) {
                goto("/dashboard");
                return;
            }

            statusPage = await res.json();
        } catch (error) {
            console.error("Error fetching status page:", error);
        }

        isPhone = window.innerWidth < 768;
    });
</script>

<div class="w-full h-screen flex flex-col px-2">
    <a href="/" class="absolute right-4 top-2 text-sm text-neutral-300 hover:underline">back home →</a>

    <div class="m-auto w-full md:w-1/2 flex flex-col">
        <h1 class="text-3xl font-bold text-neutral-300 w-full text-center mb-2">{statusPage.name}</h1>

        <p class="text-sm text-neutral-400 text-center mb-4">{statusPage.description}</p>

        <div class="flex flex-col">
            {#each statusPage.monitors as monitor}
                <div class="flex flex-col flex-1 p-2 border rounded-md my-2">
                    <div class="flex mb-2">
                        <h2 class="text-2xl font-semibold text-neutral-300">{monitor.name}</h2>

                        <div class="flex ml-auto space-x-2 my-auto">
                            <span class={`
                                px-2 rounded-md text-black my-auto
                                ${monitor.heartbeats[monitor.heartbeats.length - 1]?.status === "up" ? "bg-green-400" : "bg-red-400"}
                            `}>
                                {(monitor.heartbeats.filter(h => h.status === "up").length / monitor.heartbeats.length * 100 || 0).toFixed(2)}%
                            </span>

                            <span class="text-neutral-300 my-auto border rounded-md px-2">
                                {monitor.heartbeats.length > 0 ? monitor.heartbeats[monitor.heartbeats.length - 1]?.response_time + "ms" : "N/A"}
                            </span>
                        </div>
                    </div>

                    <div class="p-2 flex-col border rounded-md">
                        <div class="flex">
                            <div class="flex gap-1">
                                {#each Array(
                                    isPhone ? 20 : 40
                                ).fill(0).map((_, i) => i).reverse() as index}
                                    {#if index < monitor.heartbeats.length}
                                        {#if monitor.heartbeats[monitor.heartbeats.length - 1 - index]?.status === "up"}
                                            <div class="h-8 w-3 rounded-md bg-green-400"></div>
                                        {:else if monitor.heartbeats[monitor.heartbeats.length - 1 - index]?.status === "down"}
                                            <span class="h-8 w-3 rounded-md bg-red-400"></span>
                                        {/if}
                                    {:else}
                                        <div class="h-8 w-3 rounded-md bg-neutral-700"></div>
                                    {/if}
                                {/each}
                            </div>
                        </div>
                        <p class="text-neutral-400 text-sm mt-2">Checked every {monitor.heartbeat_interval} seconds</p>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</div>

// src/routes/monitor/[slug]/index.tsx
import { Meta } from "@solidjs/meta";
import { useParams } from "@solidjs/router";
import { createSignal, onMount, Show } from "solid-js";
import PingChart from "~/components/PingChart";
import { Badge } from "~/components/ui/badge";

export default function Index() {
  const { slug } = useParams();
  const [visibleHeartbeats, setVisibleHeartbeats] = createSignal(50);
  const [data, setData] = createSignal({ heartbeats: [] });
  const [infoLabel, setInfoLabel] = createSignal("");

  onMount(async () => {
    const updateScreenSize = () => {
      if (window.innerWidth >= 1400) {
        setVisibleHeartbeats(100);
      } else if (window.innerWidth >= 1200) {
        setVisibleHeartbeats(60);
      } else {
        setVisibleHeartbeats(30);
      }
    };

    window.addEventListener("resize", updateScreenSize);
    updateScreenSize();

    const res = await fetch(`/api/monitors/${slug}`);

    if (res.ok) {
      const data = await res.json();
      setData(data);
    } else {
      window.location.href = "/";
    }
  });

  return (
    <>
      <Show when={data()?.name}>
        <Meta property="og:title" content={data()?.name} />
        <Meta property="twitter:title" content={data().name} />
      </Show>
      <main class="h-screen w-full flex flex-col items-center">
        <div>
          <div class="flex p-5 flex-col lg:flex-row border bg-background mt-10 rounded-md">
            <div class="my-auto">
              <div class="flex items-center">
                <Show when={data()?.heartbeats[0]?.status == "up"}>
                  <span class="bg-green-400 mr-2 rounded-full h-5 w-5"></span>
                </Show>
                <Show when={data()?.heartbeats[0]?.status == "paused"}>
                  <span class="bg-gray-400 mr-2 rounded-full h-5 w-5"></span>
                </Show>
                <Show when={data()?.heartbeats[0]?.status == "down"}>
                  <span class="bg-red-400 mr-2 rounded-full h-5 w-5"></span>
                </Show>
                <Show when={data()?.heartbeats[0]?.status == "degraded"}>
                  <span class="bg-yellow-200 mr-2 rounded-full h-5 w-5"></span>
                </Show>
                <h1 class="font-bold text-lg mt-1">{data()?.name}</h1>
              </div>
            </div>
            <div class="ml-10 flex flex-col min-h-4">
              <div class="self-end">
                <Show when={data()?.avg_ping}>
                  <Badge class="self-end mr-2 w-fit rounded-xl">
                    Avg: {data()?.avg_ping?.toFixed(0)}ms
                  </Badge>
                </Show>
                <Badge class="self-end mr-2 w-fit rounded-xl">
                  {data()?.heartbeats[0]?.ping}ms
                </Badge>
                <Badge class="self-end w-fit rounded-xl">
                  {data()?.uptime ? data()?.uptime?.toFixed(1) + "%" : "?"}
                </Badge>
              </div>
              <div class="flex justify-end">
                {data()
                  ?.heartbeats?.slice(0, visibleHeartbeats())
                  .toReversed()
                  .map((ping) => (
                    <div
                      class="mt-1 min-h-8"
                      onMouseOver={() => {
                        setInfoLabel(ping);
                      }}
                      onMouseLeave={() => {
                        setInfoLabel("");
                      }}
                    >
                      <Show when={ping.status == "up"}>
                        <div class="w-1 h-full mx-0.5 rounded-full bg-green-400"></div>
                      </Show>
                      <Show when={ping.status == "paused"}>
                        <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-gray-400"></div>
                      </Show>
                      <Show when={ping.status == "degraded"}>
                        <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-yellow-200"></div>
                      </Show>
                      <Show when={ping.status == "down"}>
                        <div class="w-1 min-h-4 h-full mx-0.5 rounded-full bg-red-400"></div>
                      </Show>
                    </div>
                  ))}
              </div>
              <div class="min-h-[25px]">
                <Show when={infoLabel()}>
                  <Show when={infoLabel().status == "up"}>
                    <p class="text-sm mt-1 text-green-400">{`${infoLabel().time} - ${infoLabel().ping}ms`}</p>
                  </Show>
                  <Show when={infoLabel().status == "degraded"}>
                    <p class="text-sm mt-1 text-yellow-200">{`${infoLabel().time} - ${infoLabel().ping}ms`}</p>
                  </Show>
                  <Show when={infoLabel().status == "down"}>
                    <p class="text-sm mt-1 text-red-400">{`${infoLabel().time} -
                  ${infoLabel().code != 0 ? "Status: " + infoLabel().code : "Down"}`}</p>
                  </Show>
                  <Show when={infoLabel().status == "paused"}>
                    <p class="text-sm mt-1 text-gray-400">{`${infoLabel().time} - Paused`}</p>
                  </Show>
                </Show>
              </div>
            </div>
          </div>
          <div class="p-3 border h-64 mt-3 flex-grow bg-background rounded-md">
            <PingChart heartbeats={data()?.heartbeats} />
          </div>
        </div>
        <div class="mt-auto">
          <footer
            class="mt-6 mb-2 text-center text-muted-foreground"
            innerHTML={data()?.other?.footer}
          ></footer>
        </div>
      </main>
    </>
  );
}
