// src/routes/login/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import state from "$lib/state.svelte";
    import { onMount } from "svelte";
    import { setCookie } from "typescript-cookie";

    let username: string = "";
    let password: string = "";
    let error: string | null = "";

    async function login() {
        error = null;

        if (!username || !password) {
            error = "Please fill in all fields :p";
            return;
        }

        try {
            const res = await fetch("/api/auth/login", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ username, password }),
            });

            if (!res.ok) {
                const data = await res.json();
                error = data.error || "An error occurred while logging in D:";
                return;
            }

            const data = await res.json();

            state.user = {
                username: data.username,
            };

            setCookie("token", data.token);
            goto("/dashboard");
        } catch (err) {
            console.error("Login error:", err);
            error = "An unexpected error occurred :c";
        }
    }

    onMount(async () => {
        // check if a user exists, if not, redirect to create
        const exists = await fetch("/api/auth/exists", {
            method: "GET",
            headers: {
                "Content-Type": "application/json",
            },
        });

        if (exists.status === 204) {
            goto("/register");
        } else if (exists.status !== 200) {
            console.error("Failed to check if account exists:", exists.statusText);
            return;
        }
    });
</script>

<div class="flex w-full h-screen p-2">
    <div class="m-auto w-full md:w-1/4 p-4 border border-neutral-800 rounded-md flex flex-col">
        <h1 class="text-2xl font-bold text-neutral-300">Login</h1>
        <p class="text-sm text-neutral-300 mb-4">Please enter your credentials to continue :D</p>

        <label class="text-neutral-300" for="username">Username</label>
        <input
            id="username"
            type="text"
            bind:value={username}
            placeholder="Username"
        />

        <label class="text-neutral-300 mt-2" for="password">Password</label>
        <input
            id="password"
            type="password"
            bind:value={password}
            placeholder="Password"
        />

        {#if error}
            <p class="text-red-400 mt-4">{error}</p>
        {/if}

        <button
            class="mt-4 border border-neutral-700 text-neutral-300 rounded-md p-2 hover:bg-neutral-800"
            on:click={login}
        >
            Login
        </button>
    </div>
</div>

// src/routes/dash/login.tsx
import { createSignal } from "solid-js";
import { Button } from "~/components/ui/button";
import { TextField, TextFieldRoot } from "~/components/ui/textfield";
import { setCookie } from "typescript-cookie";

export default function Login() {
  const [password, setPassword] = createSignal("");
  const [username, setUsername] = createSignal("");
  const [error, setError] = createSignal("");

  const login = async () => {
    setError("");

    const response = await fetch("/api/auth/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ username: username(), password: password() }),
    }).catch((e) => {
      setError("An error occurred");
    });

    if (response.ok) {
      const data = await response.json();

      setCookie("token", data.token, { expires: 365 });

      window.location.href = "/dash";
    } else {
      const text = await response.text();

      setError(text);
    }
  };

  return (
    <main class="w-full h-screen flex items-center align-middle justify-center">
      <div class="w-full max-w-xs border-[1px] border-border p-5 bg-background rounded-lg">
        <h1 class="text-3xl font-bold text-center">Login</h1>
        <TextFieldRoot class="w-full max-w-xs  mt-2">
          <TextField
            type="username"
            placeholder="Username"
            onInput={(e) => setUsername(e.target.value)}
          />
        </TextFieldRoot>
        <TextFieldRoot class="w-full max-w-xs mt-2">
          <TextField
            type="password"
            placeholder="Password"
            onInput={(e) => setPassword(e.target.value)}
          />
        </TextFieldRoot>
        <p class="my-2 justify-start text-red-400">{error()}</p>
        <Button class="w-full max-w-xs" onClick={() => login()}>
          Login
        </Button>
      </div>
    </main>
  );
}
