// src/routes/dashboard/monitors/new/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { getCookie } from "typescript-cookie";

    let name: string = "";
    let url: string = "";

    let type: string = "http(s)";

    let url_label: string = "URL";
    $: switch (type) {
        case "http(s)":
            url_label = "URL";
            break;
        
        case "ping":
        case "tcp":
            url_label = "Host";
            break;
    }

    let url_placeholder: string = "https://";
    $: switch (type) {
        case "http(s)":
            url_placeholder = "https://";
            break;
        
        case "ping":
            url_placeholder = "1.1.1.1";
            break;
        case "tcp":
            url_placeholder = "1.1.1.1:80";
            break;
    }

    let heartbeat_interval: number = 60;
    let retries: number = 0;

    let error: string | null = null;

    async function createMonitor() {
        error = null; 

        if (!name || !url) {
            error = "Please fill in all fields :p";
            return;
        }

        try {
            const res = await fetch("/api/admin/monitors", {
                method: "PUT",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${getCookie("token")}`,
                },
                body: JSON.stringify({
                    name,
                    type,
                    url,
                    heartbeat_interval,
                    retries,
                }),
            });

            if (!res.ok) {
                const errorData = await res.json();
                error = errorData.error;
                return;
            }

            goto("/dashboard");
        } catch (err) {
            console.error("Error creating monitor:", err);
            error = "An unexpected error occurred :(";
        }
    }
</script>

<div class="flex w-full h-screen flex-col p-2">
    <div class="flex flex-col p-4 border border-neutral-800 rounded-md m-auto w-full md:w-1/3">
        <h1 class="text-2xl font-bold text-neutral-300">Add new monitor</h1>

        <label class="mt-4 text-neutral-300" for="name">Monitor Name</label>
        <input id="name" type="text" bind:value={name} />

        <label class="mt-2 text-neutral-300" for="type">Monitor Type</label>
        <select id="type" bind:value={type} class="bg-neutral-900 border border-neutral-800 rounded-md p-2">
            <option value="http(s)">HTTP(S)</option>
            <option value="ping">Ping</option>
            <option value="tcp">TCP</option>
        </select>

        <label class="mt-2 text-neutral-300" for="url">{url_label}</label>
        <input id="url" type="text" bind:value={url} placeholder={url_placeholder} />

        <label class="mt-2 text-neutral-300" for="interval">
            Heartbeat Interval (check every {heartbeat_interval} seconds)
        </label>
        <input
            id="interval"
            type="number"
            bind:value={heartbeat_interval}
            min="1"
            max="3600"
        />

        <label class="mt-2 text-neutral-300" for="type">Retries</label>
        <input id="retries" type="number" bind:value={retries} min="1" max="10" />

        {#if error}
            <p class="text-red-400 mt-4">{error}</p>
        {/if}

        <button
            class="mt-4 border text-neutral-300 rounded-md p-2 hover:bg-neutral-800 transition-colors duration-300"
            on:click={createMonitor}
        >
            Create Monitor
        </button>
    </div>
</div>

// src/routes/dash/new.tsx
import { createSignal, onMount } from "solid-js";
import { getCookie } from "typescript-cookie";
import { Badge } from "~/components/ui/badge";
import { Button } from "~/components/ui/button";
import {
  TextField,
  TextFieldRoot,
  TextFieldLabel,
} from "~/components/ui/textfield";

import {
  Checkbox,
  CheckboxControl,
  CheckboxLabel,
} from "~/components/ui/checkbox";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";

export default function New() {
  const [name, setName] = createSignal("");
  const [type, setType] = createSignal("HTTP(s)");
  const [url, setUrl] = createSignal(""); // Also counts as host
  const [interval, setInterval] = createSignal(5);
  const [_public, setPublic] = createSignal(false);
  const [webhook, setWebhook] = createSignal("");

  const label = () => {
    if (type() == "HTTP(s)") {
      return "URL";
    } else if (type() == "Ping" || type() == "TCP") {
      return "Host";
    } else if (type() == "MongoDB") {
      return "Connection String";
    } else {
      return "URL";
    }
  };

  onMount(() => {
    const token = getCookie("token");
    if (!token) {
      window.location.href = "/dash/login";
    }

    fetch("/api/auth/verify", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }).then((res) => {
      if (!res.ok) {
        window.location.href = "/dash/login";
      }
    });
  });

  const addMonitor = async () => {
    const token = getCookie("token");
    const res = await fetch("/api/admin/monitors", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        name: name(),
        url: url(),
        interval: interval(),
        webhook: webhook(),
        _public: _public(),
        type: type(),
      }),
    });

    if (res.ok) {
      window.location.href = "/dash";
    }
  };

  return (
    <main class="w-full h-screen flex">
      <div class="bg-background w-full border-border border-[1px] p-3 m-3 rounded-lg">
        <h1 class="text-2xl font-bold">New Monitor</h1>
        <TextFieldRoot class="w-full max-w-xs mt-2">
          <TextFieldLabel>Name</TextFieldLabel>
          <TextField
            type="name"
            placeholder="Name"
            onInput={(e) => setName(e.target.value)}
          />
        </TextFieldRoot>

        <Select
          options={["HTTP(s)", "Ping", "TCP", "MongoDB", "Server-Side Agent"]}
          class="w-full max-w-xs mt-2"
          itemComponent={(props) => (
            <SelectItem item={props.item}>{props.item.rawValue}</SelectItem>
          )}
          onChange={(item) => setType(item)}
          value={type()}
        >
          <label class="text-sm">Monitor Type</label>
          <SelectTrigger>
            <SelectValue<string>>
              {(state) => state.selectedOption()}
            </SelectValue>
          </SelectTrigger>
          <SelectContent />
        </Select>

        <Show when={type() != "Server-Side Agent"}>
          <TextFieldRoot class="w-full max-w-xs mt-2">
            <TextFieldLabel>{label()}</TextFieldLabel>
            <TextField
              type="url"
              placeholder={label()}
              onInput={(e) => setUrl(e.target.value)}
            />
          </TextFieldRoot>
        </Show>

        <TextFieldRoot class="w-full max-w-xs mt-2">
          <TextFieldLabel>Check Interval</TextFieldLabel>
          <TextField
            type="number"
            placeholder="Check Interval"
            onInput={(e) => setInterval(e.target.value)}
          />
        </TextFieldRoot>

        <TextFieldRoot class="w-full max-w-xs mt-2">
          <TextFieldLabel>Notification Webhook</TextFieldLabel>
          <TextField
            type="url"
            placeholder="Webhook"
            onInput={(e) => setWebhook(e.target.value)}
          />
        </TextFieldRoot>

        <Checkbox class="flex items-center my-4" onChange={(e) => setPublic(e)}>
          <CheckboxControl class="hover:cursor-pointer" />
          <CheckboxLabel class="text-sm ml-1 mt-1 font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            Make monitor public
          </CheckboxLabel>
        </Checkbox>

        <Button onClick={() => addMonitor()}>Create</Button>
      </div>
    </main>
  );
}
