// src/routes/dashboard/status_pages/new/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { getCookie } from "typescript-cookie";

    let name: string = "";
    let slug: string = "";
    let description: string = "";

    let error: string | null = null;

    async function createPage() {
        error = null; 

        if (!name || !slug) {
            error = "Please fill in all fields :p";
            return;
        }

        try {
            const res = await fetch("/api/status_pages", {
                method: "PUT",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${getCookie("token")}`,
                },
                body: JSON.stringify({
                    name,
                    slug,
                    description,
                }),
            });

            if (!res.ok) {
                const errorData = await res.json();
                error = errorData.error;
                return;
            }

            goto(`/status/${slug}`);
        } catch (err) {
            console.error("Error creating status page:", err);
            error = "An unexpected error occurred :(";
        }
    }
</script>

<div class="flex w-full h-screen flex-col p-2">
    <div class="flex flex-col p-4 border border-neutral-800 rounded-md m-auto w-full md:w-1/3">
        <h1 class="text-2xl font-bold text-neutral-300">New status page</h1>

        <label class="mt-4 text-neutral-300" for="name">Page Name</label>
        <input id="name" type="text" bind:value={name} />

        <label class="mt-2 text-neutral-300" for="url">URL Slug</label>
        <div class="flex border rounded-md">
            <div class="whitespace-pre bg-neutral-800 px-2 items-center flex text-lg text-neutral-300">
                <p>/status/</p>
            </div>
            <input class="bg-neutral-900! border-0! placeholder-neutral-400" id="url" type="text" placeholder="enter slug..." bind:value={slug} />
        </div>

        <label class="mt-2 text-neutral-300" for="interval">
            Description (optional)
        </label>
        <textarea
            id="interval"
            bind:value={description}
            class="h-24"
        ></textarea>

        {#if error}
            <p class="text-red-400 mt-4">{error}</p>
        {/if}

        <button
            class="mt-4 border text-neutral-300 rounded-md p-2 hover:bg-neutral-800 transition-colors duration-300"
            on:click={createPage}
        >
            Create Page
        </button>
    </div>
</div>

// src/routes/dashboard/status-pages/new.tsx
import { useNavigate } from "@solidjs/router";
import { createSignal } from "solid-js";
import { setKey } from "~/components/Sidebar";
import { createStatusPage } from "~/lib/server/statusPages";

export default function NewStatusPage() {
  const navigate = useNavigate();

  const [name, setName] = createSignal("");
  const [slug, setSlug] = createSignal("");
  const [error, setError] = createSignal("");

  async function create() {
    if (!name() || !slug()) {
      setError("All fields are required");
      return;
    }

    try {
      await createStatusPage({ name: name(), slug: slug() });

      setKey((k) => k + 1);
      navigate(`/status/${slug()}`);
    } catch (e) {
      console.error(e);
      setError("Failed to create status page");

      return;
    }
  }

  return (
    <main class="flex-1 flex flex-col w-full">
      <h1 class="text-2xl mt-1.75">Create New Monitor</h1>
      <div class="border rounded-md p-2 flex-1 flex flex-col mt-5">
        <label class="mb-2">Name</label>
        <input
          type="text"
          placeholder="Name"
          class="mb-2"
          value={name()}
          onInput={(e) => setName(e.currentTarget.value)}
        />

        <label class="mb-2">Slug</label>

        <div class="flex mb-2">
          <div class="bg-neutral-800 align-middle text-center flex px-4 rounded-l-md">
            <p class="my-auto text-nowrap">/status/</p>
          </div>

          <input
            type="text"
            placeholder="Slug"
            class="rounded-l-none!"
            value={slug()}
            onInput={(e) => setSlug(e.currentTarget.value)}
          />
        </div>

        <button class="mt-2" onClick={create}>
          Create
        </button>
        {error() && <p class="mt-2 text-red-400">{error()}</p>}
      </div>
    </main>
  );
}
