// src/routes/dashboard/status_pages/edit/[slug]/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    import { onMount } from "svelte";
    import { getCookie } from "typescript-cookie";

    export let data: { slug: string };

    let statusPage = {
        name: "",
        slug: data.slug,
        description: "",
        monitors: [],
    };

    let monitors: any[] = [];

    let error: string | null = null;

    onMount(async () => {
        try {
            const res = await fetch(`/api/status_pages/${data.slug}`);

            if (!res.ok) {
                goto("/dashboard");
                return;
            }

            statusPage = await res.json();
            statusPage.monitors = statusPage.monitors.map((m: any) => m.id);

            const res2 = await fetch(`/api/admin/monitors`, {
                headers: {
                    Authorization: `Bearer ${getCookie("token")}`,
                },
            });

            if (res2.ok) {
                monitors = await res2.json();
            }
        } catch (error) {
            console.error("Error fetching status page:", error);
        }
    });

    async function saveChanges() {
        error = null;

        if (!statusPage.name || !statusPage.slug) {
            error = "Please fill in mandatory fields :p";
            return;
        }

        try {
            const res = await fetch(`/api/status_pages/${data.slug}`, {
                method: "PATCH",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${getCookie("token")}`,
                },
                body: JSON.stringify({
                    name: statusPage.name,
                    slug: statusPage.slug,
                    description: statusPage.description,
                    monitors: statusPage.monitors,
                }),
            });

            if (!res.ok) {
                const errorData = await res.json();
                error = errorData.error;
                return;
            }

            goto(`/status/${statusPage.slug}`);
        } catch (err) {
            console.error("Error updating status page:", err);
            error = "An unexpected error occurred :(";
        }
    }

    function toggleMonitor(monitorId: string) {
        if (statusPage.monitors.includes(monitorId)) {
            statusPage.monitors = statusPage.monitors.filter(id => id !== monitorId);
        } else {
            statusPage.monitors = [...statusPage.monitors, monitorId];
        }
    }
</script>

<div class="flex w-full h-screen flex-col p-2">
    <div class="flex flex-col p-4 border border-neutral-800 rounded-md m-auto w-full md:w-1/3">
        <h1 class="text-2xl font-bold text-neutral-300">Update status page</h1>

        <label class="mt-4 text-neutral-300" for="name">Page Name</label>
        <input id="name" type="text" bind:value={statusPage.name} />

        <label class="mt-2 text-neutral-300" for="url">URL Slug</label>
        <div class="flex border rounded-md">
            <div class="whitespace-pre bg-neutral-800 px-2 items-center flex text-lg text-neutral-300">
                <p>/status/</p>
            </div>
            <input class="bg-neutral-900! border-0! placeholder-neutral-400" id="url" type="text" placeholder="enter slug..." bind:value={statusPage.slug} />
        </div>

        <label class="mt-2 text-neutral-300" for="interval">
            Description (optional)
        </label>
        <textarea
            id="interval"
            bind:value={statusPage.description}
            class="h-24"
        ></textarea>

        <label class="mt-2 text-neutral-300" for="monitors">
            Monitors
        </label>
        <div class="border border-neutral-700 rounded-md bg-neutral-900 max-h-48 overflow-y-auto">
            {#each monitors as monitor}
                <label class="flex items-center p-2 hover:bg-neutral-800 cursor-pointer">
                    <input
                        type="checkbox"
                        class="w-fit! mr-2"
                        checked={statusPage.monitors.find(id => id === monitor.id) !== undefined}
                        on:change={() => toggleMonitor(monitor.id)}
                    />

                    <span class="text-neutral-300">{monitor.name} ({monitor.url})</span>

                    {#if monitor.heartbeats[monitor.heartbeats.length - 1]}
                        {#if monitor.heartbeats[monitor.heartbeats.length - 1].status === "up"}
                            <span class="ml-auto text-green-400">up</span>
                        {:else if monitor.heartbeats[monitor.heartbeats.length - 1].status === "down"}
                            <span class="ml-auto text-red-400">down</span>
                        {:else}
                            <span class="ml-auto text-yellow-400">unknown</span>
                        {/if}
                    {:else}
                        <span class="ml-auto text-neutral-500">no data</span>
                    {/if}
                </label>
            {/each}

            {#if monitors.length === 0}
                <div class="p-2 text-neutral-500">No monitors available</div>
            {/if}
        </div>
        
        {#if error}
            <p class="text-red-400 mt-4">{error}</p>
        {/if}

        <div class="flex w-full space-x-2 mt-4 ">
            <a
                class="w-full text-center border text-neutral-300 rounded-md p-2 hover:bg-neutral-800 transition-colors duration-300"
                href="/dashboard"
            >
                Cancel
            </a>

            <button
                class="w-full border text-neutral-300 rounded-md p-2 hover:bg-neutral-800 transition-colors duration-300"
                on:click={saveChanges}
            >
                Save Changes
            </button>
        </div>
    </div>
</div>

// src/routes/dashboard/status-pages/edit/[slug].tsx
import { useNavigate, useParams } from "@solidjs/router";
import { createSignal, For, Show, onMount } from "solid-js";
import { getMonitors, MonitorData } from "~/lib/server/monitors";
import { getStatusPage, updateStatusPage } from "~/lib/server/statusPages";

export default function StatusPages() {
  const navigate = useNavigate();
  const params = useParams();

  const [page, setPage] = createSignal<
    { name: string; slug: string; monitors: number[] } | undefined
  >(undefined);

  const [monitors, setMonitors] = createSignal<MonitorData[]>([]);
  const [dropdownOpen, setDropdownOpen] = createSignal(false);

  onMount(async () => {
    try {
      setMonitors(await getMonitors());
    } catch (e) {
      console.error(e);
    }

    try {
      const statusPage = await getStatusPage(params.slug!);

      setPage({
        name: statusPage.name,
        slug: statusPage.slug,
        monitors: statusPage.monitors.filter(Boolean).map(Number),
      });
    } catch (e) {
      console.error(e);
      navigate("/dashboard/status-pages");
    }
  });

  function toggleMonitor(id: number) {
    setPage((p) => {
      if (!p) return p;

      return {
        ...p,
        monitors: p.monitors.includes(id)
          ? p.monitors.filter((m) => m !== id)
          : [...p.monitors, id],
      };
    });
  }

  async function save() {
    if (!page()?.name || !page()?.slug) {
      alert("All fields are required");
      return;
    }

    try {
      await updateStatusPage(params.slug!, {
        name: page()!.name,
        slug: page()!.slug,
        monitors: page()!.monitors,
      });

      navigate(`/status/${page()!.slug}`);
    } catch (e) {
      console.error(e);
      alert("Failed to update status page");
      return;
    }
  }

  return (
    <main class="flex-1 flex flex-col w-full">
      <h1 class="text-2xl mt-1.75">Edit: {page()?.name}</h1>

      <div class="border rounded-md p-2 flex-1 flex flex-col mt-5">
        <label class="mb-2">Name</label>
        <input
          type="text"
          placeholder="Name"
          class="mb-2"
          value={page()?.name}
          onInput={(e) =>
            setPage((p) => p && { ...p, name: e.currentTarget.value })
          }
        />

        <label class="mb-2">Slug</label>

        <div class="flex mb-2">
          <div class="bg-neutral-800 align-middle text-center flex px-4 rounded-l-md">
            <p class="my-auto text-nowrap">/status/</p>
          </div>

          <input
            type="text"
            placeholder="Slug"
            class="rounded-l-none!"
            value={page()?.slug}
            onInput={(e) =>
              setPage((p) => p && { ...p, slug: e.currentTarget.value })
            }
          />
        </div>

        <label class="mb-2">Monitors</label>
        <div class="relative mb-2">
          <button
            class="w-full border rounded-md p-2 text-left flex justify-between items-center bg-neutral-900 min-h-10 hover:bg-neutral-900! hover:border-neutral-700!"
            onClick={() => setDropdownOpen(!dropdownOpen())}
          >
            <span class="flex flex-wrap gap-1">
              <Show
                when={(page()?.monitors.length ?? 0) > 0}
                fallback={
                  <span class="text-neutral-500">Select monitors...</span>
                }
              >
                <For each={page()?.monitors ?? []}>
                  {(id) => {
                    const monitor = monitors().find((m) => m.monitor.id === id);

                    return (
                      <span class="px-2 py-0.5 rounded-md border text-sm flex items-center gap-2">
                        {monitor?.monitor.name ?? `#${id}`}
                        <button
                          type="button"
                          class="no-style text-red-400 text-xl hover:cursor-pointer"
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleMonitor(id);
                          }}
                        >
                          ×
                        </button>
                      </span>
                    );
                  }}
                </For>
              </Show>
            </span>
            <span class="ml-2">{dropdownOpen() ? "▲" : "▼"}</span>
          </button>

          <Show when={dropdownOpen()}>
            <div class="absolute z-10 w-full mt-1 border rounded-md bg-neutral-900 max-h-60 overflow-y-auto">
              <Show
                when={monitors().length > 0}
                fallback={
                  <div class="p-2 text-neutral-500">No monitors available</div>
                }
              >
                <For each={monitors()}>
                  {(monitor) => {
                    const selected = () =>
                      page()?.monitors.includes(monitor.monitor.id) ?? false;

                    return (
                      <div
                        class="p-2 hover:bg-neutral-800 cursor-pointer flex items-center gap-2"
                        classList={{ "bg-neutral-800": selected() }}
                        onClick={() => toggleMonitor(monitor.monitor.id)}
                      >
                        <span>{monitor.monitor.name}</span>
                        <span class="text-neutral-500 text-sm ml-auto">
                          {monitor.monitor.type}
                        </span>
                      </div>
                    );
                  }}
                </For>
              </Show>
            </div>
          </Show>
        </div>

        <button class="button mt-2" onClick={save}>
          Save
        </button>
      </div>
    </main>
  );
}
